name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  package:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - run: python -m pip install --upgrade pip setuptools
      - run: python -m pip install -e '.[test,release]'
      - run: python -m pytest --cov
      - run: ruff check . && mypy src
      - run: python -m build && twine check dist/*
      - uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: dist/*
      - uses: pypa/gh-action-pypi-publish@ed0c53930ec7c2dffb3f1624b391f57b7d0970dc # v1
      - uses: softprops/action-gh-release@6cbd405e6b9a013e02cd4bf5a7f64b8cc8d3a764 # v2
        with:
          files: dist/*
